version: '3.8'

services:
  app:
    build:
      context: .
    container_name: brands-app
    volumes:
      - .:/var/www
    ports:
      - "8000:9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: brands-db
    environment:
      MYSQL_DATABASE: brand_toplist
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
